-- INSERT INTO users (username, email, password) VALUES ('jomama', 'admin@localhost', '123');
-- INSERT INTO users (username, email, password) VALUES ('johndoe', 'johndoe@localhost', '456');
-- INSERT INTO users (username, email, password) VALUES ('janedoe', 'janedoe@localhost', '789');
-- INSERT INTO users (username, email, password) VALUES ('jimmydoe', 'jimmydoe@localhost', '101112');
